// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://klajzvehgpbgvecnaogp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtsYWp6dmVoZ3BiZ3ZlY25hb2dwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMTI3OTMsImV4cCI6MjA2NjY4ODc5M30.80zRnGPeoD2g9c8cGLfpPs5o_2y373f25kHwGd4xyXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);